server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Tohanos/springcloud-config.git
          search-paths: config
          clone-on-start: true
          #don't forget username and password
  application:
    name: config-server

logging:
  level:
    org.springframework.cloud: DEBUG
