spring:
  application:
    name: spring-eshop
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
#    username: postgres
#    password: postgres
  flyway:
    baseline-on-migrate: true
management:
  endpoint:
    web:
      exposure:
        include: "logfile"



